branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - 
    - "@semantic-release/npm"
    - npmPublish: true
      tarballDir: dist
  - "@semantic-release/github"
  -
    - "@semantic-release/git"
    - assets:
        - package.json
        - package-lock.json
      message: "chore(release): ${nextRelease.version} [skip ci]"
