issuer: https://token.actions.githubusercontent.com
subject: repo:mikes-rowdy-bunch/reshi-pic:ref:refs/heads/main

permissions:
  contents: write
  packages: write
  issues: write
  pull_requests: write
